[pytest]
addopts =
    --cov=backup_engine
    --cov=backupsys_api
    --cov=backupsys_cli
    --cov=build_exe
    --cov=config_manager
    --cov=credential_store
    --cov=integrity_scheduler
    --cov=notification_utils
    --cov=setup_wizard
    --cov=transport_utils
    --cov=watcher
    --cov=tests
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=60
testpaths = tests